<a href="https://colab.research.google.com/github/factorLee/DeepLearningfromScratch01_PKNU/blob/main/AI09_lecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

\

## One-hot encoding

In [ ]:
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train = x_train/255.
x_test = x_test/255.
x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse = False)
y_train = encoder.fit_transform(y_train.reshape(-1,1))
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

## 손실함수:MSE

In [ ]:
import numpy as np
y_hat=[0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0]
y=[0,0,1,0,0,0,0,0,0,0]
np.sum((np.array(y_hat)-np.array(y))**2)*0.5

0.09750000000000003

In [ ]:
def mean_squared_error(y,y_hat):
    return 0.5*np.sum((y-y_hat)**2)
    

In [ ]:
mean_squared_error(np.array(y),np.array(y_hat))

0.09750000000000003

## 손실함수:Cross-entropy

In [ ]:
y = np.array(y)
y_hat = np.array(y_hat)
delta = 1e-7


In [ ]:
-1*np.sum(y*np.log(y_hat+delta))

0.510825457099338

In [ ]:
def cross_entropy_error(y,y_hat):
    delta = 1e-7
    return -1*np.sum(y*np.log(y_hat+delta))

In [ ]:
cross_entropy_error(y,y_hat)

0.510825457099338

## 미니배치(Mini batch)

In [ ]:
np.random.choice(10,3)

array([5, 4, 0])

In [ ]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size,batch_size)
print(batch_mask)
x_batch = x_train[batch_mask]
y_batch = y_train[batch_mask]


[54082 34028 36695 30246 53313 57002 47109 38053 52797 13059]


In [ ]:
y_batch

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
y_hat_batch = np.random.uniform(size=(100)).reshape(10,10)

In [ ]:
print(y_batch)
print(y_hat_batch)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0.61325574 0.68131024 0.84711606 0.59313166 0.34006486 0.34694717
  0.62676818 0.40750531 0.71517665 0.60741071]
 [0.24096865 0.39322761 0.14265042 0.96497966 0.51601761 0.86529088
  0.82295659 0.525772   0.68423581 0.77838767]
 [0.48648777 0.84475968 0.66376734 0.01954702 0.67349063 0.80162996
  0.67258896 0.00640025 0.7644062  0.53065604]
 [0.5964664  0.49326329 0.02779739 0.3882493  0.16072632 0.14215142
  0.35710413 0.30534143 0.27691816 0.76189562]
 [0.72338609 0.4716521  0.38994289 0.69310186 0.7313837  0.46209702
  0.79617143 0.31060449 0.86572182 0.70528808]
 [0.61729325 0.26957736 0.44891838 0.53609344 0.79678273 0.47577922
  0.36336033 0.08804962 0.

In [ ]:
np.sum(-1*y_batch*np.log(y_hat_batch))/10


[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
def cross_entropy_error(y,y_hat):
    if y.ndim == 1:
        y_hat = y_hat.reshape(1,y_hat.size)
        y = y.reshape(1,y.size)
    delta = 1e-7

    batch_size = y.shape[0]
    return -1*np.sum(y*np.log(y_hat+delta))/batch_size


In [ ]:
cross_entropy_error(y_batch,y_hat_batch)

0.596356396000766

In [ ]:
cross_entropy_error(y,y_hat)

0.510825457099338